corePizzaProject/Controllers/AdminController.cs
using corePizzaProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.Encodings.Web;

namespace corePizzaProject.Controllers
{
    public class AdminController : Controller
    {
        private ApplicationDbContext _context;
        public AdminController()
        {
            _context = new ApplicationDbContext();
        }
        [Authorize(Roles = "admin")]
        public IActionResult Index()
        {
            var data = _context.Users.ToList();
            return View(data);
        }
        public ActionResult Delete(int id)
        {
            var data = _context.Users.FirstOrDefault(x => x.UserId == id);
            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, User1 user)
        {
            try
            {
                _context.Users.Remove(user);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Details(int id)
        {
            var data = _context.Users.FirstOrDefault(x => x.UserId == id);
            return View(data);
        }
        [Authorize(Roles = "admin")]
        public IActionResult DisplayCategories()
        {
            var data = _context.Categories.ToList();
            return View(data);
        }
        public ActionResult CategoryDetails(int id)
        {
            var data = _context.Categories.FirstOrDefault(x => x.CategoryId == id);
            return View(data);
        }
        public IActionResult EditCategory(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                ViewBag.Message = HtmlEncoder.Default.Encode("Invalid Id of the Author");
                return View();
            }
            else
            {
                var data = _context.Categories.FirstOrDefault(x => x.CategoryId == id);
                return View(data);
            }
        }
        [HttpPost]
        public IActionResult EditCategory(Category category)
        {
            _context.Categories.Update(category);
            _context.SaveChanges();
            return RedirectToAction("DisplayCategories");
        }
        public ActionResult DeleteCategory(int id)
        {
            var data = _context.Categories.FirstOrDefault(x => x.CategoryId == id);
            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCategory(int id, Category category)
        {
            try
            {
                _context.Categories.Remove(category);
                _context.SaveChanges();
                return RedirectToAction("DisplayCategories");
            }
            catch
            {
                return View();
            }
        }
        public IActionResult CreateCategory()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateCategory(Category category)
        {
            _context.Categories.Add(category);
            _context.SaveChanges();
            return RedirectToAction("DisplayCategories");
        }
        public IActionResult CreateProduct()
        {
            var categories = _context.Products.Select(a => new SelectListItem { Value = a.CategoryId.ToString(), Text = a.Category.Name }).Distinct().ToList();
            ViewBag.categories = categories;
            return View();
        }
        [HttpPost]
        public IActionResult CreateProduct(Product pro)
        {
            _context.Products.Add(pro);
            _context.SaveChanges();
            return View("ViewProducts");
        }
        [Authorize(Roles = "admin")]
        public IActionResult ViewProducts()
        {
            var products = _context.Products.Select(p => new
            {
                Id = p.ProductId,
                Name = p.Name,
                Price = p.Price,
                Image = p.Image,
                Quantity = p.AvailableQuantity,
                CategoryName = p.Category.Name,
            }).ToList();
            return View(products);
        }
    }
}

corePizzaProject/Controllers/CartController.cs
using corePizzaProject.Helpers;
using corePizzaProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.IdentityModel.Tokens;


namespace corePizzaProject.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext _context;
        public CartController()
        {
            _context = new ApplicationDbContext();
        }

        [Authorize(Roles = "user")]
        public IActionResult Index()
        {
            var cart = SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (cart.IsNullOrEmpty())
            {
                return RedirectToAction("EmptyCart");
            }
            else
            {
                ViewBag.cart = cart;
                ViewBag.total = cart.Sum(item => item.Product.Price * item.Quantity);
                return View();
            }
        }
        public IActionResult Buy(int id)
        {
            if (SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart") == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item() { Product = _context.Products.SingleOrDefault(p => p.ProductId == id), Quantity = 1 });
                SessionHelper.setObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<Item> cart = SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                int index = isExists(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new Item() { Product = _context.Products.SingleOrDefault(p => p.ProductId == id), Quantity = 1 });
                }
                SessionHelper.setObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction("Index");
        }
        public int isExists(int id)
        {
            List<Item> cart = SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.ProductId == id)
                {
                    return i;
                }
            }
            return -1;
        }
        [Authorize(Roles = "user")]
        public IActionResult Remove(int id)
        {
            List<Item> cart = SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            int index = isExists(id);
            cart.RemoveAt(index);
            SessionHelper.setObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "user")]
        public IActionResult CheckOut()
        {
            List<Item> cart = SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            ViewBag.count = cart.Count();
            ViewBag.cart = cart;
            ViewBag.total = cart.Sum(item => item.Product.Price * item.Quantity);
            return View();
        }
        public IActionResult MakePayment()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "user")]
        public IActionResult MakePayment(Address addr)
        {
            _context.Addresses.Add(addr);
            _context.SaveChanges();
            ViewBag.address = addr;
            List<Item> cart = SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            ViewBag.count = cart.Count();
            ViewBag.cart = cart;
            ViewBag.total = cart.Sum(item => item.Product.Price * item.Quantity);
            return View();
        }
        [Authorize(Roles = "user")]
        public IActionResult EmptyCart()
        {
            List<Item> cart = SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (cart.IsNullOrEmpty())
            {
                return View();
            }
            else
            {
                cart.Clear();
                SessionHelper.setObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return View();
        }
        public IActionResult Payment()
        {
            List<Item> cart = SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            ViewBag.count = cart.Count();
            ViewBag.cart = cart;
            ViewBag.total = cart.Sum(item => item.Product.Price * item.Quantity);
            var addr = _context.Addresses.FirstOrDefault();
            ViewBag.address = addr;
            return View();
        }
    }
}

corePizzaProject/Controllers/ProductController.cs
using corePizzaProject.Models;
using Microsoft.AspNetCore.Mvc;

namespace corePizzaProject.Controllers
{
    public class ProductController : Controller
    {
        private ApplicationDbContext _context;
        public ProductController()
        {
            _context = new ApplicationDbContext();
        }
        public IActionResult Index()
        {
            var products = _context.Products.Select(p => new
            {
                Id = p.ProductId,
                Name = p.Name,
                Price = p.Price,
                Image = p.Image,
                Quantity = p.AvailableQuantity,
                CategoryName = p.Category.Name,
            }).ToList();
            return View(products);
        }
        public IActionResult ViewDetails(int id)
        {
            /*var data = _context.Products.FirstOrDefault(x => x.ProductId == id);*/
            var products = _context.Products.Where(p => p.ProductId == id).Select(p => new
            {
                Id = p.ProductId,
                Name = p.Name,
                Price = p.Price,
                Image = p.Image,
                Quantity = p.AvailableQuantity,
                CategoryName = p.Category.Name,
            }).ToList();
            ViewBag.Result = products;
            return View(products);
        }
    }
}

corePizzaProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizza Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/corePizzaProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Pizza Store</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" id="home-btn" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" id="privacy-btn" asp-action="Privacy">Privacy</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="AdminPage">Admin Page</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="Index">UserDetails</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="ViewProducts">Products</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="DisplayCategories">Categories</a>
                                </li>
                                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                                    <li class="nav-item">
                                        <a class="text-danger nav-link btn btn-outline-info me-2" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                    </li>
                                </ul>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Product" id="available-products" asp-action="Index">Available Products</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Cart" id="cart" asp-action="Index">View Cart</a>
                                </li>
                                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                                    <li class="nav-item">
                                        <a class="text-danger btn btn-outline-info me-2" asp-area="" id="logout" asp-controller="Account" asp-action="Logout">Logout</a>
                                    </li>
                                </ul>
                            }
                        }
                        else
                        {
                            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                                <li class="nav-item" style="float:right;">
                                    <a class="btn btn-outline-light me-2" asp-area="" asp-controller="Account" id="register-btn" asp-action="Register">Register</a>
                                </li>
                                <li class="nav-item">
                                    <a class="btn btn-outline-warning me-2" asp-area="" asp-controller="Account" id="login-btn" asp-action="Login">Login</a>
                                </li>
                            </ul>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="container">
        <footer class="my-5 pt-5 text-body-secondary text-center text-small">
            <hr />
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a asp-controller="Home" asp-action="Index" class="nav-link px-2 text-body-secondary">Home</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
                <li class="nav-item"><a asp-controller="Home" asp-action="Privacy" class="nav-link px-2 text-body-secondary">Privacy</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
            </ul>
            <p class="text-center text-body-secondary">&copy; 2023 Laptop Store, Inc</p>
        </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>